### ISSUE TITLE
Packed Enum Support?

### ISSUE THREAD

**Issue by oshaboy** [ProtoByter/packed#2]
Packed enums are usually like regular enums but stored in the minimum type able to hold every value

**Comment by ExoSkye** [comment]
I'll look into it, however I'm slightly busy with irl stuff rn, but I'll take a look when I can

**Comment by ExoSkye** [comment]
Added in https://github.com/ProtoByter/packed/commit/bb6d2fedf513e6f74e2f3ca947c74dc8c2bcc830
