### ISSUE TITLE
struct declaration containing a comma will break

### ISSUE THREAD

**Issue by giuliomoro** [ProtoByter/packed#3]
e.g.:

```
PACKED_STRUCT(MyStruct {
float a;
std::array<float,2> b;
uint8_t c;
}) myStruct;
```
will break as the C-preprocessor will see two arguments to the macro (one before, one after the `,`).

**Comment by ExoSkye** [comment]
I also just noticed, that whilst this is still a bug you're using the library incorrectly:
```
PACKED_STRUCT(MyStruct {
float a;
std::array<float,2> b;
uint8_t c;
}) myStruct;
```

For one `myStruct` and `MyStruct` don't match up, two, if this is a C struct definition (which I think it is based on the two names), you need to have a typedef in front of it, ie:
```
typedef PACKED_STRUCT(MyStruct {
float a;
std::array<float,2> b;
uint8_t c;
}) MyStruct;
```

**Comment by ExoSkye** [comment]
Fixed in https://github.com/ProtoByter/packed/commit/bb6d2fedf513e6f74e2f3ca947c74dc8c2bcc830
